### ISSUE TITLE
[QUESTION] why using gunicorn?

### ISSUE THREAD

**Issue by H3zi** [anthonycorletti/cloudrun-fastapi#21]
Hi,
FastAPI docs say that when running in a system that manages distributed containers (e.g. K8s) it is better to run a single Uvicorn process.
See here: https://fastapi.tiangolo.com/deployment/docker/#replication-number-of-processes 

I believe Cloud Run falls under that group of systems that manage container clusters, load balancing, etc'...
So the question is, why use Gunicron to manage the workload?
WDYT?

**Comment by anthonycorletti** [comment]
great question! sebastian makes a great point and i would suggest deploying your container in the best way that suits your use case. for something like cloud run i think the approach of using a single uvicorn worker is fine. you could also just run one gunicorn-uvicorn worker. there is no particularly rigorous reason why ive done it this way. ive been using fastapi for a few years now so i might be a bit stuck in my ways haha. ill see if i have time to make some changes. open to pull requests if you'd like to make one for uvicorn deployment support!

**Comment by anthonycorletti** [comment]
@H3zi lmk what you think of https://github.com/anthonycorletti/cloudrun-fastapi/tree/docker/single-uvicorn-worker-per-container/  hope it helps!

The more I think about it I definitely think it depends on your applications. If you don't want to rely on thread management directly through fastapi alone, gunicorn+uvicorn would be good to use.

**Comment by anthonycorletti** [comment]
sounds cool! ill close this out.
